version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: tybaloo/backend:latest
    build:
      context: ./FootballMatches
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    image: tybaloo/frontend:latest
    build:
      context: ./football-matches-app
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
